apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: component-sample3
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: component-sample3
    app.kubernetes.io/part-of: application-sample
  name: component-sample3
spec:
  host: route111
  path: /
  port:
    targetPort: 1111
  to:
    kind: Service
    name: component-sample3
    weight: null
status: {}
