apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: component-sample3
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: backend3
    app.kubernetes.io/part-of: application-sample
  name: component-sample3
  namespace: maysun
spec:
  ports:
  - port: 1111
    targetPort: 1111
  selector:
    app.kubernetes.io/instance: component-sample3
status:
  loadBalancer: {}
